Update build_test.yml

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -1,6 +1,6 @@
 # This is a basic workflow to help you get started with Actions
 
-name: CMake Build Test
+name: CMake Build Test in all Folders
 
 # Controls when the workflow will run
 on:
@@ -16,7 +16,6 @@ on:
 env:
   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
   BUILD_TYPE: Debug
-  PROJECT_FOLDER: GPIOEXTI0
   
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -30,15 +29,11 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
 
-      - name: Verify Working Directory Exists
+      - name: Verify Folders Exist
         run: |
-          if [ -z "${{ env.PROJECT_FOLDER }}" ]; then
-            echo "Error: PROJECT_FOLDER is not set!"
-            exit 1
-          fi
-
-          if [ ! -d "${{ env.PROJECT_FOLDER }}" ]; then
-            echo "Error: Folder '${{ env.PROJECT_FOLDER }}' does not exist!"
+          FOLDERS=$(ls -d */ 2>/dev/null || echo "")
+          if [ -z "$FOLDERS" ]; then
+            echo "Error: No project folders found!"
             exit 1
           fi
         shell: bash
@@ -48,14 +43,13 @@ jobs:
 
       - name: Install Ninja
         uses: seanmiddleditch/gha-setup-ninja@v3
+
+      - name: Find All Folders and Configure CMake Build ${{env.BUILD_TYPE}}
+        run: |
+          for dir in */ ; do
+            echo "Processing folder: $dir"
+            cmake -B "$GITHUB_WORKSPACE/build" -DCMAKE_BUILD_TYPE="${{ env.BUILD_TYPE }}"
+            cmake --build "$GITHUB_WORKSPACE/build" --config "${{ env.BUILD_TYPE }}"
+          done
+        shell: bash        
   
-      - name: Configure CMake
-        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
-        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
-        working-directory: ${{env.PROJECT_FOLDER}}
-        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
-  
-      - name: Build ${{env.BUILD_TYPE}}
-        working-directory: ${{env.PROJECT_FOLDER}}
-        # Build your program with the given configuration
-        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
